#!/bin/bash
set -e
./bin/nex -e -o gork.n.go parse/gork.nex
if [ $# -eq 1 ] && [ $1 == '-v' ]
then
	echo Building gork...
	tail -n +1 <<< `./bin/goyacc -o gork.y.go -v /tmp/gork.y.output parse/gork.y`
	go build -v -o gork gork.go types.go gork.y.go gork.n.go
else
	tail -n +1 <<< `./bin/goyacc -o gork.y.go -v /tmp/gork.y.output parse/gork.y` > /tmp/goyacc.out
	go build -o gork gork.go types.go gork.y.go gork.n.go
fi
if [ $# -eq 1 ] && [ $1 == '--clean' ]
then
	echo Cleaning gork...
	echo Deleting
	echo - `rm -v gork.n.go`
	echo - `rm -v gork.y.go`
	echo - `rm -v gork`
fi
